### ISSUE TITLE
Can't get variation key in object kameleoonClient.Types.Variation

### ISSUE THREAD

**Issue by JKbidi** [Kameleoon/client-swift#2]
When I call "getActiveFeatures() -> [String : kameleoonClient.Types.Variation]" I can't use data within kameleoonClient.Types.Variation. Actually I would like to get all active features key and their Variation key

**Comment by AMelyohin** [comment]
Thank you for the report. Could you please provide more details including the actual result, the expected result, and the code snippet which causes the issue to appear?

**Comment by JKbidi** [comment]
I would like to get the key of a variation when I map on the result of the function getActiveFeatures().

![Capture d’écran 2024-04-11 à 10 35 12](https://github.com/Kameleoon/client-swift/assets/165906593/8c480dc5-779c-44a4-901c-763e8facec8d)

I saw the key "on" when I put a break point but I can't get it. It seems like the object Types.Variation has nothing within

![Capture d’écran 2024-04-11 à 10 34 31](https://github.com/Kameleoon/client-swift/assets/165906593/4a04ee78-0d79-4086-8a12-592493d2bc2b)

**Comment by DmitryAE** [comment]
Hello @JKbidi ,

We extend our sincere apologies for the inconvenience you encountered. We are pleased to inform you that the issue has been addressed and resolved in [Swift SDK version 4.1.4](https://github.com/Kameleoon/client-swift/blob/main/CHANGELOG.md#414---2024-04-17). You can install the version through Swift Package or Cocoapods.

Should you require any further assistance or have additional inquiries, please do not hesitate to reach out.

Best regards,
Dmitry.

**Comment by JKbidi** [comment]
Thank you 🙏
